# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Ency14 Blog
tagline:          Search Groep
description:      Ency14 Blog
url:              http://wimvanacker.github.io

author:
  name:           'Wim Van Acker'
  url:            

paginate:         5

github:
  repo:           https://github.com/wimvanacker/wimvanacker.github.io
